:lang:        ja
:icons:       font
:docinfo:
// 目次を表示する。左側に表示する。
:toc: left
// 第何レベルまで目次を表示するか。
:toclevels: 2
// ドキュメントの説明。
:description: Asciidotの文法のクイックリファレンスです。
// 章番号を付けるか。属性を定義しておくだけで章番号が付けられる。
:sectnums:
// デフォルトの章番号の接頭辞「Chapter.」が表示されないよう、値を空で設定する。
:sectanchors:
// ソースコードをハイライトする。
:source-highlighter: coderay
// UIマクロを有効にする
:experimental:

// 各ラベルの日本語定義
:toc-title: 目次
:preface-title: はじめに
:appendix-caption: 付録
:caution-caption: 注意
:example-caption: 例
:figure-caption: 図
:important-caption: 重要
:last-update-label: 最終更新
:manname-title: 名前
:note-caption: 注記
:preface-title: まえがき
:table-caption: 表
:tip-caption: ヒント
:toc-title: 目次
:untitled-label: 無題
:version-label: バージョン
:warning-caption: 警告
:listing-caption: リスト

// 変数定義。各資産のルートフォルダ
:imagesdir: images
:includedir: _includes
:sourcedir: source



= Asciidoctor 文法クイックリファレンス
:linkattrs:

== パラグラフ

=== 通常
----
include::{includedir}/ex-text.adoc[tags=通常のパラグラフ]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=通常のパラグラフ]
====


=== 改行
----
include::{includedir}/ex-text.adoc[tags=改行]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=改行]
====



=== リテラル
----
include::{includedir}/ex-text.adoc[tags=リテラル]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=リテラル]
====

=== 脚注
----
include::{includedir}/ex-text.adoc[tags=脚注]
----

[.result]
====
include::{includedir}/ex-text.adoc[tag=脚注]
====

NOTE: <<脚注ブロック,脚注ブロック>>のような書き方も可能です。


=== リード
----
include::{includedir}/ex-text.adoc[tag=リード]
----

[.result]
====
include::{includedir}/ex-text.adoc[tag=リード]
====

NOTE: Asciidoctorのデフォルトスタイルシートの場合、序文の最初のパラグラフにリードパラグラフのスタイルが自動で適用されます。

=== パラグラフ、リテラル、脚注ブロックの詳しい例
****
Asciidoctor User Manual の下記セクションを参考にしてください。

* http://asciidoctor.org/docs/user-manual/#paragraph[Paragraphs]
* http://asciidoctor.org/docs/user-manual/#literal-text-and-blocks[Literal Text and Blocks]
* http://asciidoctor.org/docs/user-manual/#admonition[Admonitions]

****


== テキストフォーマット
=== 太字、イタリック、モノスペース
----
include::{includedir}/ex-text.adoc[tag=太字-イタリック-モノスペース]
----

[.result]
====
include::{includedir}/ex-text.adoc[tag=太字-イタリック-モノスペース]
====

=== マーク、カスタムスタイル
----
include::{includedir}/ex-text.adoc[tag=マーク-カスタムスタイル]
----

[.result]
====
include::{includedir}/ex-text.adoc[tag=マーク-カスタムスタイル]
====

=== スーパースクリプト、サブスクリプト
----
include::{includedir}/ex-text.adoc[tag=スーパースクリプト-サブスクリプト]
----

[.result]
====
include::{includedir}/ex-text.adoc[tag=スーパースクリプト-サブスクリプト]
====

=== カーブクォート、アポストロフィ
----
include::{includedir}/ex-text.adoc[tag=カーブクォート-アポストロフィ]
----

[.result]
====
include::{includedir}/ex-text.adoc[tag=カーブクォート-アポストロフィ]
====

NOTE: アポストロフィは日本語では使用しないので英語のままにしています。


=== テキストフォーマットの例は
****
Asciidoctor User Manual の下記セクションを参考にしてください。

* http://asciidoctor.org/docs/user-manual/#bold-and-italic[Bold and Italic Formatting]
* http://asciidoctor.org/docs/user-manual/#curved[Quotation Marks and Apostrophes]
* http://asciidoctor.org/docs/user-manual/#subscript-and-superscript[Subscript and Superscript]
* http://asciidoctor.org/docs/user-manual/#mono[Monospace Formatting]
* http://asciidoctor.org/docs/user-manual/#custom-styling-with-attributes[Custom Styling with Attributes]
* http://asciidoctor.org/docs/user-manual/#pass-mac[Passthrough Macros]

****

== ドキュメントヘッダー
IMPORTANT: ヘッダーはオプションです。

CAUTION: ヘッダーは空行であることは許容されません。またコンテンツと最低一行以上は間隔を開ける必要があります。


=== タイトルのみ
----
include::{includedir}/ex-header-title.adoc[tag=通常]
----

=== タイトルと著者
----
include::{includedir}/ex-author.adoc[tag=通常]
----

NOTE: 著者が複数人の場合はセミコロンで区切って記載してください。

=== タイトルと著者とリビジョン
----
include::{includedir}/ex-rev.adoc[tag=通常]
----

IMPORTANT: 著者を定義していないとリビジョンを定義することはできません。

=== タイトルと属性
----
include::{includedir}/ex-header-attr.adoc[tag=通常]
----

[[セクションタイトル]]
== セクションタイトル

=== 記事形式
----
include::{includedir}/ex-section.adoc[tag=記事形式]
----

[.result]
====
include::{includedir}/ex-section.adoc[tag=記事形式]
====

WARNING: 記事形式（デフォルト）を使用する場合、レベル0のタイトル(ドキュメントのタイトルなど)は１つしか定義できません。
また必ずドキュメントヘッダーに定義してください。

NOTE: ``=``の数がHTMLのヘッダーレベルと一致しています。例えば__レベル１のセクションのタイトル__は``<h2>``に変換されます。

=== 本形式
----
include::{includedir}/ex-section.adoc[tag=本形式]
----

[.result]
====
include::{includedir}/ex-section.adoc[tag=本形式]
====

=== idを指定
----
[[primitives-nulls]]
== プリミティブ型とnull
----

.セクションアンカーとリンク


`sectanchors`::
このドキュメント属性が設定されている場合、セクションアイコンアンカーが表示されます。


`sectlinks`::
このドキュメント属性が設定されている場合、セクションタイトルが自分自身へのリンクになります。
これによりユーザはセクションをブックマークすることができます。


NOTE: セクションタイトルアンカーは、プロパティをレンダリングするデフォルトのAsciidoctorのスタイルに依存します。


== 別ファイルのインクルード

=== ドキュメントをインクルード
----
include::{includedir}/ex-include.adoc[tag=通常]
----

CAUTION: Asciidoctorはコンテントを隔てるために、隣接したincludeステートメントの間に空行を挿入するようなことはしません。
空行を勝手に挿入すると、セクションタイトルを無効にしてしまうような思わぬ結果を招いてしまうからです。


.URIによるコンテンツのインクルード
----
include::{includedir}/ex-include.adoc[tags=URI]
----

NOTE: URIによるコンテンツのインクルードは危険があります。
セーフモードがSECUREかそれ以上の場合は無効になるからです。
たとえセーフモードがSECIREよりも低いとしても、
allow-uri-read AsciidoctorがURIからコンテンツを読み込むために``allow-uri-read``属性を設定する必要があります。


== 水平罫線と改ページ
=== 水平罫線
----
include::{includedir}/ex-hr.adoc[tag=水平罫線]
----

=== 改ページ
----
include::{includedir}/ex-hr.adoc[tag=改ページ]
----

== リスト
=== 順序無しリスト
----
include::{includedir}/ex-u-list.adoc[tag=順序無しリスト]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tag=順序無しリスト]
====

NOTE: リストの前後には空白行が必須です。

TIP: 行コメントで二つのリストを分割できます。
コメント中の(`+^+`)はオプションですが、この行がリストの終わりということを意味するマーカです。

=== ネストした順序無しリスト
----
include::{includedir}/ex-u-list.adoc[tag=ネストした順序無しリスト]
----

NOTE: 順序無しリストのマーカはlink:http://asciidoctor.org/docs/user-manual/#custom-markers[blocks style]で変更可能です。

=== チェックリスト
----
include::{includedir}/ex-u-list.adoc[tag=チェックリスト]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tag=チェックリスト]
====

TIP: チェックリストはlink:http://asciidoctor.org/docs/user-manual/#checklist[font-based icons and be interactive]を使うこともできます。

=== 順序有りリスト
----
include::{includedir}/ex-u-list.adoc[tag=順序有りリスト]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tag=順序有りリスト]
====


=== ネストした順序有りリスト
----
include::{includedir}/ex-u-list.adoc[tag=ネストした順序有りリスト]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tag=ネストした順序有りリスト]
====


=== 最もネストした順序有りリスト
----
include::{includedir}/ex-u-list.adoc[tag=最もネストした順序有りリスト]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tag=最もネストした順序有りリスト]
====


TIP: 順序有りリスト用にAsciidoctorはlink:http://asciidoctor.org/docs/user-manual/#numbering-styles[numeration styles]をサポートしています。
``lowergreek``や``decimal-leading-zero``などが用意されています。



=== ラベル(単一行)
----
include::{includedir}/ex-dlist.adoc[tag=ラベル(単一行)]
----

[.result]
====
include::{includedir}/ex-dlist.adoc[tag=ラベル(単一行)]
====


=== ラベル(複数行)
----
include::{includedir}/ex-dlist.adoc[tag=ラベル(複数行)]
----

[.result]
====
include::{includedir}/ex-dlist.adoc[tag=ラベル(複数行)]
====


=== Q&A
----
include::{includedir}/ex-dlist.adoc[tag=Q&A]
----

[.result]
====
include::{includedir}/ex-dlist.adoc[tag=Q&A]
====

=== リストとラベルの組み合わせ
----
include::{includedir}/ex-dlist.adoc[tag=リストとラベルの組み合わせ]
----

[.result]
====
include::{includedir}/ex-dlist.adoc[tag=リストとラベルの組み合わせ]
====

TIP: ラベルはネスト可能です。行の冒頭のスペースは重要ではありません(あってもなくてもいいです)。


=== アウトライン中の複雑なコンテンツ
----
include::{includedir}/ex-dlist.adoc[tag=アウトライン中の複雑なコンテンツ]
----

[.result]
====
include::{includedir}/ex-dlist.adoc[tag=アウトライン中の複雑なコンテンツ]
====

== リンク
=== 通常のリンク
----
include::{includedir}/ex-url.adoc[tag=通常のリンク]
----

[.result]
====
include::{includedir}/ex-url.adoc[tag=通常のリンク]
====

=== スペースと特殊文字を含んだリンク
----
include::{includedir}/ex-url.adoc[tag=スペースと特殊文字を含んだリンク]
----

[.result]
====
include::{includedir}/ex-url.adoc[tag=スペースと特殊文字を含んだリンク]
====


=== Windows版リンク
----
include::{includedir}/ex-url.adoc[tag=Windows版リンク]
----

[.result]
====
include::{includedir}/ex-url.adoc[tag=Windows版リンク]
====


=== 相対パス
----
include::{includedir}/ex-url.adoc[tag=相対パス]
----

[.result]
====
include::{includedir}/ex-url.adoc[tag=相対パス]
====


=== メールとIRC
----
include::{includedir}/ex-url.adoc[tag=メールとIRC]
----

[.result]
====
include::{includedir}/ex-url.adoc[tag=メールとIRC]
====


=== 属性付きのリンク(Asciidoctor限定)
----
include::{includedir}/ex-url.adoc[tag=属性付きのリンク]
----

[.result]
====
include::{includedir}/ex-url.adoc[tag=属性付きのリンク]
====

NOTE: 属性付きリンクはAsciidoctor固有の機能です。
機能を有効にするにはドキュメントの属性に`linkattrs`を指定してください。
機能有効時は、カンマを含むリンクはクォートで囲む必要があります。



=== インラインアンカー
----
include::{includedir}/ex-xref.adoc[tag=インラインアンカー]
----

[.result]
====
include::{includedir}/ex-xref.adoc[tag=インラインアンカー]
====


=== 内部相互参照
----
include::{includedir}/ex-xref.adoc[tag=内部相互参照]
----

[.result]
====
include::{includedir}/ex-xref.adoc[tag=内部相互参照]
====

=== ドキュメント間の相互参照
----
include::{includedir}/ex-xref.adoc[tag=ドキュメント間の相互参照]
----


== 画像
ドキュメント属性のlink:http://asciidoctor.org/docs/user-manual/#set-the-images-directory[imagedir](デフォルトは空文字)を
起点にした相対パスを指定します。
全ての画像パスに対して共通のパスをハードコードするのを避けるために``imagedir``の指定を推奨します。

``imagedir``は絶対パス、相対パス、URLを指定できます。
絶対パスとURLの場合はimagedirのプレフィックスは付きません。

=== ブロック画像
----
include::{includedir}/ex-image.adoc[tags=通常]

include::{includedir}/ex-image.adoc[tags=alt属性使用]

include::{includedir}/ex-image.adoc[tags=属性使用]

include::{includedir}/ex-image.adoc[tags=URL指定]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=通常]

include::{includedir}/ex-image.adoc[tags=alt属性使用]

include::{includedir}/ex-image.adoc[tags=属性使用]

include::{includedir}/ex-image.adoc[tags=URL指定]
====



=== インラン画像
----
include::{includedir}/ex-image.adoc[tags=インライン]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=インライン]
====


IMPORTANT: ``image``というキーワードの後にある二つのコロンはブロック要素の画像を示し、
一つの時はインライン要素の画像を示します。文章と同じ行に画像を挿入するならインランを使いますが、
それ以外の場合場合はブロック要素の画像を使用すべきです。


.位置を指定したインライン画像
----
include::{includedir}/ex-image.adoc[tags=位置を指定したインライン]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=位置を指定したインライン]
====

NOTE: link:http://asciidoctor.org/docs/user-manual/#putting-images-in-their-place[画像の位置とフレーム]には様々な属性を指定できます。

=== 画像データ埋め込み
----
include::{includedir}/ex-image.adoc[tags=画像データ埋め込み]
----


NOTE: ``data-uri``を設定すると、アイコンも含め全ての画像がドキュメントの中にlink:https://developer.mozilla.org/en-US/docs/data_URIs[data-uri]と埋め込まれます。

TIP: ``data-uri``の代わりに、コマンドラインで``-a data-uri``オプションを付けることでも可能です。


== 動画

=== ブロック要素
----
include::{includedir}/ex-video.adoc[tags=ブロック要素]


include::{includedir}/ex-video.adoc[tags=属性指定]
----

=== Youtube
----
include::{includedir}/ex-video.adoc[tags=動画youtube]
----

[.result]
====
include::{includedir}/ex-video.adoc[tags=動画youtube]
====


=== Vimeo
----
include::{includedir}/ex-video.adoc[tags=動画vimeo]
----

[.result]
====
include::{includedir}/ex-video.adoc[tags=動画vimeo]
====

TIP: link:http://asciidoctor.org/docs/user-manual/#video[追加の属性とオプション]を設定することで動画を制御できます。



== ソースコード
=== インライン要素
----
include::{includedir}/ex-text.adoc[tags=インラインコード]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=インラインコード]
====

=== リテラル（１行）
----
include::{includedir}/ex-literal.adoc[tags=リテラル行コード]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=リテラル行コード]
====


=== リテラル（ブロック要素）
----
include::{includedir}/ex-literal.adoc[tags=リテラルブロックコード]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=リテラルブロックコード]
====

[listing]
=== タイトル付きブロック要素（シンタックスハイライトなし）
....
include::{includedir}/ex-listing.adoc[tags=タイトル付きブロック要素（シンタックスハイライトなし）]
....

[.result]
====
include::{includedir}/ex-listing.adoc[tags=タイトル付きブロック要素（シンタックスハイライトなし）]
====

[listing]
=== タイトル付きブロック要素（シンタックスハイライトあり）
....
include::{includedir}/ex-src.adoc[tags=タイトル付きブロック要素（シンタックスハイライトあり）]
....

[.result]
====
include::{includedir}/ex-src.adoc[tags=タイトル付きブロック要素（シンタックスハイライトあり）]
====


[listing, subs="specialcharacters"]
=== 吹き出し付きブロック要素
....
include::{includedir}/ex-callout.adoc[tags=吹き出し付きブロック要素]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=吹き出し付きブロック要素]
====


[listing, subs="specialcharacters"]
=== いろいろな吹き出し付きブロック要素
....
include::{includedir}/ex-callout.adoc[tags=いろいろな吹き出し付きブロック要素]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=いろいろな吹き出し付きブロック要素]
====


[listing, subs="specialcharacters"]
=== 吹き出し付きXMLブロック要素
....
include::{includedir}/ex-callout.adoc[tags=吹き出し付きXMLブロック要素]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=吹き出し付きXMLブロック要素]
====

[listing]
=== ソースコードファイル読み込み
....
include::{includedir}/ex-src.adoc[tags=ソースコードファイル読み込み]
....

[listing]
=== ソースコードファイル読み込み(ソースコードフォルダからの相対パス指定)
....
[source,java]
----
\include::{sourcedir}/StringUtils.java[]
----
....

[.result]
====
[source,java]
----
include::{sourcedir}/StringUtils.java[]
----
====

[listing]
=== ソースコードファイル読み込み(インデント指定)
....
[source,java,indent=0]
----
\include::{sourcedir}/StringUtils.java[lines=5..7]
----

[source,java,indent=1]
----
\include::{sourcedir}/StringUtils.java[lines=5..7]
----


[source,java,indent=2]
----
\include::{sourcedir}/StringUtils.java[lines=5..7]
----
....


[.result]
====
[source,java,indent=0]
----
include::{sourcedir}/StringUtils.java[lines=5..7]
----

[source,java,indent=1]
----
include::{sourcedir}/StringUtils.java[lines=5..7]
----

[source,java,indent=2]
----
include::{sourcedir}/StringUtils.java[lines=5..7]
----
====


[NOTE]
====
* ``indent``が0の場合、インデントは除去されます。（タブは4つのスペースに置換されます。）
* ``indent``が1以上の場合、基本のインデントレベルが指定した値になります。（タブは4つのスペースに置換されます。）
====

=== 区切り文字なしのブロック要素
----
include::{includedir}/ex-src.adoc[tags=区切り文字なしのブロック要素]
----

[.result]
====
include::{includedir}/ex-src.adoc[tags=区切り文字なしのブロック要素]
====


[IMPORTANT]
=== シンタックスハイライトを有効にするには
====
``source-highlighter``属性をドキュメントヘッダーに付けるか、実行時に引数で渡すことで有効になります。

 :source-highlighter: pygments

値は``coderay``、``highlightjs``、``prettify``、``pygments``を指定できます。
====

== その他のブロック
=== サイドバー
----
include::{includedir}/ex-sidebar.adoc[tags=サイドバー]
----

[.result]
====
include::{includedir}/ex-sidebar.adoc[tags=サイドバー]
====


NOTE: どんなブロックでも、ブロックの上にタイトルを付けることができます。
タイトルは``.``で始まるテキスト行です。
``.``のあとにスペースを定義することはできません。

=== 例
----
include::{includedir}/ex-example.adoc[tags=通常の例]
----

[.result]
--
include::{includedir}/ex-example.adoc[tags=通常の例]
--


=== 脚注
----
include::{includedir}/ex-admon.adoc[tags=ブロック]
----

[.result]
=====
include::{includedir}/ex-admon.adoc[tags=ブロック]
=====


[TIP]
.脚注と吹き出しのアイコン
====
Asciidoctorではlink:http://fortawesome.github.io/Font-Awesome/[Font-Awesome^]とCSSを使って "`描く`" ことができます。

これらを使うには、ドキュメント属性の``font``に値``icons``を設定してください.
設定するとHTML生成時にそれぞれの脚注に対して最適なアイコンが選択されます。

link:http://asciidoctor.org/docs/user-manual/#inline-icons[inline]と
link:http://asciidoctor.org/docs/user-manual/#size-rotate-and-flip[styled]でも
アイコンは使用可能です。
====


=== ブロッククォート
----
include::{includedir}/ex-quote.adoc[tags=ブロック]

include::{includedir}/ex-quote.adoc[tags=インライン]

include::{includedir}/ex-quote.adoc[tags=引用なし]

include::{includedir}/ex-quote.adoc[tags=リンクテキスト]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=ブロック]

include::{includedir}/ex-quote.adoc[tags=インライン]

include::{includedir}/ex-quote.adoc[tags=引用なし]

include::{includedir}/ex-quote.adoc[tags=リンクテキスト]
====


=== 簡略ブロッククォート(Asciidoctor限定)
----
include::{includedir}/ex-quote.adoc[tags=簡略記法]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=簡略記法]
====


=== Airクォート(Asciidoctor限定)
----
include::{includedir}/ex-quote.adoc[tags=air]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=air]
====

=== 変換せずに出力
----
include::{includedir}/ex-pass.adoc[tags=変換せずに出力]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=変換せずに出力]
====


=== オープン
----
include::{includedir}/ex-open.adoc[tags=基本]

include::{includedir}/ex-open.adoc[tags=ソース]
----

[.result]
====
include::{includedir}/ex-open.adoc[tags=基本]

include::{includedir}/ex-open.adoc[tags=ソース]
====

=== カスタム置換
-----
include::{includedir}/ex-listing.adoc[tags=カスタム置換]
-----

[.result]
====
include::{includedir}/ex-listing.adoc[tags=カスタム置換]
====


== ID,ロール,オプションの指定
=== ブロックへのIDとロールの指定
----
[[goals]]
[role="incremental"]
* Goal 1
* Goal 2
----

=== ブロックへのIDとROLEの指定(簡略記法)
----
[#goals.incremental]
* Goal 1
* Goal 2
----

[TIP]
====
* 簡略記法で複数の``role``を指定するには、``.``区切りで指定してください。
* 簡略記法において``id``と``role``の順番は特に関係ありません。
====


=== テキストへのIDとロールの指定
----
[[free_the_world]][big goal]_free the world_
----

=== テキストへのIDとロールを指定する(簡略記法、Asciidoctor限定)
----
[#free_the_world.big.goal]_free the world_
----

=== クオートで囲まれたテキストへのROLEの指定
----
[rolename]`monospace text`
----


=== オプションの指定
----
[options="header,footer,autowidth"]
|===
|Cell A |Cell B
|===
----


=== オプションの指定(簡略記法、Asciidoctor限定)
----
[%header%footer%autowidth]
|===
|Cell A |Cell B
|===
----

== コメント
=== 行コメント
----
include::{includedir}/ex-comment.adoc[tags=行]
----

=== ブロックコメント
----
include::{includedir}/ex-comment.adoc[tags=ブロック]
----


== テーブル
=== タイトル、ヘッダ付き2×3
----
include::{includedir}/ex-table.adoc[tags=基本]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=基本]
====

<1> ``cols``属性が未指定の場合は、最初の１行目のカラムの数がテーブルの列数となります。
<2> 最初の行のあとが空行の場合は、最初の行はヘッダー行とみなされます。

=== AsciiDocコンテンツ入り
----
include::{includedir}/ex-table.adoc[tags=AsciiDocコンテンツ入り]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=AsciiDocコンテンツ入り]
====

=== CSV読み込み
----
include::{includedir}/ex-table.adoc[tags=CSV]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=CSV]
====

=== CSV読み込み(簡略記法、Asciidoctor限定）
----
include::{includedir}/ex-table.adoc[tags=CSV簡略記法]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=CSV簡略記法]
====


=== CSVファイル読み込み
----
|===
include::customers.csv[]
|===
----

=== DSV読み込み(簡略記法、Asciidoctor限定)
----
include::{includedir}/ex-table.adoc[tags=DSV簡略記法]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=DSV簡略記法]
====

=== 整形、セル結合
----
include::{includedir}/ex-table.adoc[tags=整形とセル結合]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=整形とセル結合]
====


== UIマクロ

IMPORTANT: マクロを使用可能にするには、ドキュメントヘッダーぶ``experimental``属性を指定する必要があります。

=== キーボードショートカット
----
include::{includedir}/ex-ui.adoc[tags=キーボード]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=キーボード]
====

=== メニュー
----
include::{includedir}/ex-ui.adoc[tags=メニュー]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=メニュー]
====


=== ボタン
----
include::{includedir}/ex-ui.adoc[tags=ボタン]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=ボタン]
====
