spring:
  main:
    banner-mode: 'console'
  datasource:
    url: jdbc:mysql://localhost:3306/journal
    username: springboot
    password: springboot
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    hibernate:
      naming:
        strategy: org.hibernamte.cfg.ImprovedNamingStrategry
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    rest:
      base-path: /api

      
  
