-- SECURITY:USER_ACCOUNT
DROP TABLE IF EXISTS account;
CREATE TABLE account(
	ID SERIAL,
	ACCOUNT_NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ENABLED BOOL DEFAULT true
 );

-- JOURNAL TABLE:ENTITY
DROP TABLE IF EXISTS entry;
CREATE TABLE entry(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(255) DEFAULT NULL,
  SUMMARY VARCHAR(255) DEFAULT NULL,
  CREATED DATETIME DEFAULT NULL,
  PRIMARY KEY (ID)
);