
// tag::para[]
旅はこの間の月曜の午後、アントウェルペンから始まった。
我々はコーヒーを切実に欲しているが、あえてオフィスのドアを開こうとしない。

それはソースコードの分断と死を意味する。
// end::para[]


// tag::通常のパラグラフ[]
パラグラフは特別なマークアップは不要です。
一行から複数行に渡り連続して記述するだけです。

新らしいパラグラフを始める時は、最低一行の空白行を入れてください。
// end::通常のパラグラフ[]


// tag::改行[]
ルビーは赤 +
トパーズは青

[%hardbreaks]
ルビーは赤
トパーズは青
// end::改行[]



// tag::リテラル[]
通常のパラグラフ1

 １つ以上の空白で始まる連続した行はリテラルパラグラフとみなされます。
 リレラルパラグラフはpreformatted textとして扱われます。
 textは固定幅のフォントで表示され、
 改行はそのまま改行とみなされます。

通常のパラグラフ2
// end::リテラル[]


// tag::脚注[]

NOTE: 脚注パラグラフは補助的な情報を示すものです。
パラグラフ冒頭のラベルによって使い分けることができます。

NOTE以外のデフォルトで用意されている脚注を示します。
TIP: チップスを記述します。

IMPORTANT: 重要事項を記述します。

WARNING: 警告を記述します。

CAUTION: 注意を記述します。

// end::脚注[]


// tag::リード[]
[.lead]
このパラグラフはリードパラグラフのスタイル(文字が大きいスタイル)が適用されます。
// end::リード[]


// tag::太字-イタリック-モノスペース[]
*太字の語句* と **太**字の文**字**

_イタリックの語句_ と __イタ__リックの文__字__

*_太字のイタリックの語句_* と **__太字のイタ__**リックの文**__字__**

`モノスペースの語句`と``モノ``スペースの文``字``

`*モノスペースの太字の語句*` と ``**モノ**``スペースの太字の語``**句**``

`_モノスペースのイタリックの語句_` と ``__モノ__``スペースのイタリックの文``__字__``

`*_モノスペースの太字のイタリックの語句_*` と ``**__モノ__**``スペースの太字のイタリックの``**__文字__**``
// end::太字-イタリック-モノスペース[]


// tag::マーク-カスタムスタイル[]
狼男は #シナモン# アレルギーです。

狼男たちは [.small]#小さい活字# を読みましたか?

全ての [.underline]#コア# はどこに流れたのですか?

[.line-through]#10# 20台のVMを用意する必要があります。

[.big]#い# ったん無限ループが起きると

// end::マーク-カスタムスタイル[]



// tag::スーパースクリプト-サブスクリプト[]
^スーパー^スクリプトの語句

~サブ~スクリプトの語句
// end::スーパースクリプト-サブスクリプト[]


// tag::カーブクォート-アポストロフィ[]
"`ダブルカーブクォート`"

'`シングルカーブクォート`'

Olaf's desk was a mess.

All of the werewolves`' desks were a mess.

Olaf had been with the company since the `'60s.

// end::カーブクォート-アポストロフィ[]



// tag::external[]
= セッションタイトル　レベル１
レベル1

== セッションタイトル レベル２
レベル２

=== セッションタイトル レベル3
レベル３

==== セッションタイトル レベル4
レベル４

===== セッションタイトル レベル5
レベル５

====== セッションタイトル レベル6
レベル６

======= セッションタイトル レベル7
レベル７は存在しない
// end::external[]

// tag::インラインコード[]
`types` や `methods` のような参照コード。
// end::インラインコード[]
